### ISSUE TITLE
macOS support ?

### ISSUE THREAD

**Issue by LuoZijun** [danlrobertson/rust-cpuid#1]
System: macOS 10.13.3
Rust: 1.25.0-nightly (4d2d3fc5d 2018-02-13)
Cargo: 0.26.0-nightly (1d6dfea44 2018-01-26)
Command: `cargo build --verbose`
Output:

```
   Compiling cpuid v0.1.0 (file:///Users/bob/Project/rust-cpuid)
     Running `rustc --crate-name cpuid src/lib.rs --crate-type rlib --emit=dep-info,link -C debuginfo=2 -C metadata=449ac65e85c8a712 -C extra-filename=-449ac65e85c8a712 --out-dir /Users/bob/Project/rust-cpuid/target/debug/deps -C incremental=/Users/bob/Project/rust-cpuid/target/debug/incremental -L dependency=/Users/bob/Project/rust-cpuid/target/debug/deps -L native=/Users/bob/Project/rust-cpuid/target/debug/build/cpuid-23f99a72e3746434/out`
error: could not find native static library `cpuid`, perhaps an -L flag is missing?

error: Could not compile `cpuid`.

Caused by:
  process didn't exit successfully: `rustc --crate-name cpuid src/lib.rs --crate-type rlib --emit=dep-info,link -C debuginfo=2 -C metadata=449ac65e85c8a712 -C extra-filename=-449ac65e85c8a712 --out-dir /Users/bob/Project/rust-cpuid/target/debug/deps -C incremental=/Users/bob/Project/rust-cpuid/target/debug/incremental -L dependency=/Users/bob/Project/rust-cpuid/target/debug/deps -L native=/Users/bob/Project/rust-cpuid/target/debug/build/cpuid-23f99a72e3746434/out` (exit code: 101)
```

`target/debug/build/cpuid-xxxxxx/stderr`:

```
clang: error: unsupported option '--64'
ar: illegal option combination for -r
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
```

**Comment by dlrobertson** [comment]
Sure, I can look into this.

Note: This crate was more or less me playing around with rust and figuring out how to make a "safe-ish" wrapper around a function written in assembly. If [libcpuid](https://github.com/anrieff/libcpuid) is available to you, a more stable method of getting info about your CPU in rust would be to use [zsiciarz/rust-cpuid](https://github.com/zsiciarz/rust-cpuid).

**Comment by LuoZijun** [comment]
The `zsiciarz/rust-cpuid` project havn't write one `build.rs` for auto compile `libcpuid` .

And i like your asm code :))

**Comment by dlrobertson** [comment]
:+1: I'll try to get it compiling on my mac then. I'm starting to wonder if maybe using inline assembly would be best.

**Comment by LuoZijun** [comment]
Yeah, that's a good idea.

**Comment by dlrobertson** [comment]
53636f6b7e98d736aff19d6a9179ab8e632491df and b167de7a79da5d703be44a57bf6ba5c4654de432 switches to using inline assembly and compiles on my Mac
